image: ruby:2.4.2

stages:
  - build
  - create-server
  - delete-server

variables:
  CERT_PATH: certs
  INSTANCE_NAME: stage-host-${CI_COMMIT_REF_SLUG}
  DOCKER_HUB_REPO: 's1spinoza/gitlab_otus'
  PATH_TO_DOCKERRFILE: docker-monolith
  DOCKER_IMAGE: "reddit:${CI_COMMIT_REF_SLUG}"
  DOCKER_IMAGE_HUB: "${DOCKER_HUB_REPO}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}"

build_job:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - cd ${PATH_TO_DOCKERRFILE}
    - docker build -t ${DOCKER_IMAGE} .
    - docker image tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_HUB}
    - docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PASS}
    - docker push ${DOCKER_IMAGE_HUB}

create-server:
  image: docker:latest
  services:
    - docker:dind
  stage: create-server
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    untracked: true
  when: manual
  script:
    - apk update && apk add ca-certificates curl jq
    - base=https://github.com/docker/machine/releases/download/v0.14.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && install /tmp/docker-machine /usr/local/bin/docker-machine
    - docker-machine -s ${CERT_PATH} create --driver google --google-project docker-201808 --google-machine-image https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts --google-machine-type n1-standard-1 --google-zone europe-west1-b ${INSTANCE_NAME}
    - eval $(docker-machine -s ${CERT_PATH} env --shell sh ${INSTANCE_NAME})
    - docker pull ${DOCKER_IMAGE_HUB}
    - docker run -d -p 9292:9292 ${DOCKER_IMAGE_HUB}
  environment:
    name: branch/${CI_COMMIT_REF_SLUG}
    on_stop: delete-server
#  only:
#    - branches
#  except:
#    - master

delete-server:
  image: docker:latest
  services:
    - docker:dind
  stage: delete-server
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    untracked: true
  when: manual
  script:
    - apk update && apk add ca-certificates curl jq
    - base=https://github.com/docker/machine/releases/download/v0.14.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && install /tmp/docker-machine /usr/local/bin/docker-machine
    - docker-machine -s ${CERT_PATH} rm -y ${INSTANCE_NAME}
  environment:
    name: branch/${CI_COMMIT_REF_SLUG}
    action: stop


