comment:
  image:
    repository: s1spinoza/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: s1spinoza/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: s1spinoza/ui
    tag: latest
    service:
      externalPort: 9292
