version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${VERSION_UI}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${VERSION_POST}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${VERSION_COMMENT}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
