kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: jnhPVIMNM/RUZXrXJHbGUjk6mjeocIOBZSShRwjevj0=
      - identity: {}
