version: '3.3'
services:
  ui:
    command: puma --debug -w 2
    volumes:
      - app_ui:/app
  post:
    volumes:
      - app_post:/app
  comment:
    volumes:
      - app_comment:/app

volumes:
  app_ui:
  app_post:
  app_comment:
